services:
  - type: web
    name: openmosque-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: FIREBASE_CREDENTIALS_JSON
        sync: false
      - key: APP_CORS_ALLOWED_ORIGINS
        sync: false
      - key: CLOUDFLARE_R2_ACCESS_KEY
        sync: false
      - key: CLOUDFLARE_R2_SECRET_KEY
        sync: false
      - key: CLOUDFLARE_R2_ENDPOINT
        sync: false
      - key: CLOUDFLARE_R2_BUCKET
        sync: false
      - key: CLOUDFLARE_R2_PUBLIC_URL
        sync: false
